backend:
  name: git-gateway
  branch: master
media_folder: "/images/uploads"
collections:
  [
    {
      name: "posts",
      label: "Post",
      folder: "/text",
      filter: { field: language, value: en },
      fields: [{ label: "Description", name: "description", widget: "string" }],
    },
  ]
