backend:
  name: git-gateway
  branch: master
media_folder: "/images/uploads"
collections:
  [
    {
      name: "posts",
      label: "Post",
      folder: "_posts",
      filter: { field: language, value: en },
      fields: [{ label: "Description", name: "description", widget: "text" }],
    },
  ]
